INSERT INTO clientes (nombre, apellido, email, create_at, deleted) VALUES ('Karemen', 'Lopez', 'karemen_lopex@hotmail.com', '1986-08-21', FALSE);
INSERT INTO clientes (nombre, apellido, email, create_at, deleted) VALUES ('Samata', 'DeGarcia', 'samtnha_degarcia@hotmail.com', '1988-02-02', FALSE);
INSERT INTO clientes (nombre, apellido, email, create_at, deleted) VALUES ('Jesus', 'perex', 'jesusito_bonito@hotmail.com', '2019-12-07', FALSE);
INSERT INTO clientes (nombre, apellido, email, create_at, deleted) VALUES ('armando', 'rodriguez', 'armando_rodriguez@hotmail.com', '1988-08-04', FALSE);
INSERT INTO clientes (nombre, apellido, email, create_at, deleted) VALUES ('Marco', 'farias', 'cus_farias@hotmail.com', '1988-01-02', FALSE);
INSERT INTO clientes (nombre, apellido, email, create_at, deleted) VALUES ('Laura', 'frias', 'lau_frias@hotmail.com', '1992-02-05', FALSE);
INSERT INTO clientes (nombre, apellido, email, create_at, deleted) VALUES ('cinthia', 'rosas', 'cinthia_rodlop@hotmail.com', '1990-04-13', FALSE);
INSERT INTO clientes (nombre, apellido, email, create_at, deleted) VALUES ('Karen', 'Ortiz', 'karen_pelirroja@hotmail.com', '1993-12-25', FALSE);
INSERT INTO clientes (nombre, apellido, email, create_at, deleted) VALUES ('Karen', 'brambila', 'karen_brambila_guerita@hotmail.com', '1998-10-10', FALSE);
